# Generated by Django 5.2.5 on 2025-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_AD', '0004_actionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='categorie',
        ),
    ]
