# Generated by Django 5.2.5 on 2025-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_AD', '0005_remove_annonce_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='color',
            field=models.CharField(choices=[('primary', 'Bleu'), ('success', 'Vert'), ('danger', 'Rouge'), ('warning', 'Jaune'), ('info', 'Cyan'), ('secondary', 'Gris')], default='secondary', max_length=20),
        ),
    ]
