# Generated by Django 5.2.5 on 2025-09-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_AD', '0006_categorie_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_AD.annonce')),
            ],
        ),
    ]
